// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LessonsBot_DB.Migrations
{
    [DbContext(typeof(DbProvider))]
    partial class DbProviderModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("LessonsBot_DB.ModelsDb.Bot", b =>
                {
                    b.Property<Guid>("IdBot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("IdValueService")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimeOutResponce")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdBot");

                    b.ToTable("Bots");
                });

            modelBuilder.Entity("LessonsBot_DB.ModelsDb.PeerProp", b =>
                {
                    b.Property<Guid>("IdPeerProp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BotIdBot")
                        .HasColumnType("TEXT");

                    b.Property<long>("IdPeer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastResult")
                        .HasColumnType("TEXT");

                    b.Property<int>("TypeLesson")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdPeerProp");

                    b.HasIndex("BotIdBot");

                    b.ToTable("PeerProps");
                });

            modelBuilder.Entity("LessonsBot_DB.ModelsDb.PeerProp", b =>
                {
                    b.HasOne("LessonsBot_DB.ModelsDb.Bot", null)
                        .WithMany("PeerProps")
                        .HasForeignKey("BotIdBot");
                });

            modelBuilder.Entity("LessonsBot_DB.ModelsDb.Bot", b =>
                {
                    b.Navigation("PeerProps");
                });
#pragma warning restore 612, 618
        }
    }
}
